import React from 'react';
import { User, Bot, ShieldCheck } from 'lucide-react';
import AIProviderBadge from './AIProviderBadge';

export default function MessageBubble({ message }) {
  const isUser = message.role === 'user';

  // Clean formatting artifacts if any
  const cleanContent = (message.content || '')
    .replace(/^<think>[\s\S]*?<\/think>/g, '')
    .trim();

  return (
    <div className={`flex items-start gap-3 my-3 ${isUser ? 'flex-row-reverse' : ''}`}>
      {/* Avatar */}
      <div
        className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 border ${
          isUser
            ? 'bg-sky-600 border-sky-500 text-white shadow-2xs'
            : 'bg-emerald-600 border-emerald-500 text-white shadow-2xs'
        }`}
      >
        {isUser ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
      </div>

      {/* Bubble Container */}
      <div
        className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm flex flex-col gap-2 ${
          isUser
            ? 'bg-sky-600 text-white rounded-tr-xs shadow-2xs'
            : 'bg-white text-slate-800 border border-slate-200/80 rounded-tl-xs shadow-2xs'
        }`}
      >
        {/* Assistant Header Badge */}
        {!isUser && (
          <div className="flex items-center justify-between gap-2 pb-2 border-b border-slate-100 mb-1">
            <AIProviderBadge
              provider={message.provider_used || 'OpenAI (gpt-5-nano)'}
              isFallback={false}
            />
            {message.intent && (
              <span className="text-[10px] bg-slate-100 text-slate-600 border border-slate-200 px-2 py-0.5 rounded-full font-bold">
                {message.intent}
              </span>
            )}
          </div>
        )}

        {/* Message Content */}
        <div className="whitespace-pre-wrap leading-relaxed text-sm">
          {cleanContent}
        </div>

        {/* Assistant Footer Metadata Tag */}
        {!isUser && (
          <div className="mt-2 pt-2 border-t border-slate-100 flex items-center gap-1.5 text-[10px] text-slate-400 font-medium">
            <ShieldCheck className="w-3 h-3 text-emerald-500 shrink-0" />
            <span>Generated by GPT-5 Nano · Based on validated report data · Evidence-backed explanation · Not a medical diagnosis</span>
          </div>
        )}
      </div>
    </div>
  );
}
